# Question 1 — Implement Convolution from Scratch

## Write a Python program that performs 2-D convolution/filtering without using a built-in convolution function.

Use the following input:

Input:

```bash
1 1 1 0 0
0 1 1 1 0
0 0 1 1 1
0 0 1 1 0
0 1 1 0 0
```
Filter:
```bash
1 0 1
0 1 0
1 0 1
```

Use stride = 1 and padding = 0.

Your program must:
- Store the input and filter using NumPy arrays.
- Slide the filter over the input matrix.
- Compute the dot product at every valid location.
- Print the complete output feature map.
- Print the output shape.
- Briefly explain how changing the stride from 1 to 2 would affect the output.


In [1]:
import numpy as np

In [ ]:
# Define the input matrix and the kernel matrix
input_matrix = np.array([
    [1, 1, 1, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 1, 1],
    [0, 0, 1, 1, 0],
    [0, 1, 1, 0, 0]
])

# Kernel Matrix: 3 × 3
kernel = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
])

print("Input Matrix Shape:", input_matrix.shape)
print("Kernel Shape:", kernel.shape)

Input Matrix Shape: (5, 5)
Kernel Shape: (3, 3)


In [3]:
# Define the convolution function
def convolve_2d(input_matrix, kernel, stride=1):
    
    input_height, input_width = input_matrix.shape
    kernel_height, kernel_width = kernel.shape

    output_height = (input_height - kernel_height) // stride + 1
    output_width = (input_width - kernel_width) // stride + 1

    output = np.zeros(
        (output_height, output_width),
        dtype=np.result_type(input_matrix, kernel)
    )

    # Slide the filter over every valid location.
    for row in range(output_height):
        for col in range(output_width):
            start_row = row * stride
            start_col = col * stride

            region = input_matrix[
                start_row:start_row + kernel_height,
                start_col:start_col + kernel_width
            ]

            # Dot product: multiply corresponding values and sum.
            output[row, col] = np.sum(region * kernel)

    return output


In [ ]:
# Generate the feature map by convolving the input matrix with the kernel
feature_map = convolve_2d(input_matrix, kernel, stride=1)

In [5]:
# Print the feature map
print("Output feature map:")
print(feature_map)
print("Output shape:", feature_map.shape)

Output feature map:
[[4 3 4]
 [2 4 3]
 [2 3 4]]
Output shape: (3, 3)


In [6]:
# Changging the stride to 2
feature_map_stride_2 = convolve_2d(input_matrix, kernel, stride=2)

In [7]:
# Print the feature map with stride=2
print("Output feature map with stride=2:")
print(feature_map_stride_2)
print("Output shape with stride=2:", feature_map_stride_2.shape)

Output feature map with stride=2:
[[4 4]
 [2 4]]
Output shape with stride=2: (2, 2)


### Briefly explain how changing the stride from 1 to 2 would affect the output.

Changing the stride from 1 to 2 makes the filter move two cells at a time, both horizontally and vertically, instead of one. For the given 5 × 5 input, 3 × 3 filter, and no padding, the output feature map decreases from 3 × 3 to 2 × 2. This reduces the number of dot-product calculations from 9 to 4, making the computation faster. However, the filter skips intermediate positions, so the output captures less spatial detail.